version: "3.8"

services:
  db:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 8000:${SERVER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy